CREATE TABLE IF NOT EXISTS profile (
    id INT AUTO_INCREMENT NOT NULL,
    ra VARCHAR(100) NOT NULL,
    senha TEXT NOT NULL,
    types TEXT NOT NULL,
    CONSTRAINT id_profile PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS admin (
    idAdmin INT AUTO_INCREMENT NOT NULL,
    id INT NOT NULL,
    CONSTRAINT id_admin PRIMARY KEY (idAdmin),
    CONSTRAINT id_admin_profile FOREIGN KEY (id) REFERENCES profile (id)
);
CREATE TABLE IF NOT EXISTS paises (
    idPais INT AUTO_INCREMENT NOT NULL,
    nomePais TEXT NOT NULL,
    tituloPais TEXT NOT NULL,
    imagemPais MEDIUMBLOB NOT NULL,
    informacoes TEXT NOT NULL,
    cadastrado TEXT NOT NULL,
    CONSTRAINT idPais PRIMARY KEY (idPais)
);

CREATE TABLE IF NOT EXISTS activity (
    idActiviy INT AUTO_INCREMENT NOT NULL,
    idPais TEXT NOT NULL,
    chave TEXT NOT NULL,
    datas DATE NOT NULL,
    professor TEXT NOT NULL,
    perguntas TEXT NOT NULL,
    tempo INT NOT NULL,
    alunos TEXT NOT NULL,
    iniciado TEXT NOT NULL,
    stage INT NOT NULL,
    active TEXT NOT NULL,
    CONSTRAINT idActiviy PRIMARY KEY (idActiviy)
);

CREATE TABLE IF NOT EXISTS history (
    idHistory INT AUTO_INCREMENT NOT NULL,
    alunos TEXT NOT NULL,
    CONSTRAINT idHistory PRIMARY KEY (idHistory)
);

INSERT INTO paises (idPais, nomePais, tituloPais, imagemPais, informacoes, cadastrado) VALUES
(1, 'Afghanistan', '', '', '', 'nao'),
(2, 'Albania', '', '', '', 'nao'),
(3, 'Algeria', '', '', '', 'nao'),
(4, 'Andorra', '', '', '', 'nao'),
(5, 'Angola', '', '', '', 'nao'),
(6, 'Antigua and Barb.', '', '', '', 'nao'),
(7, 'Argentina', '', '', '', 'nao'),
(8, 'Armenia', '', '', '', 'nao'),
(9, 'Ashmore and Cartier Is.', '', '', '', 'nao'),
(10, 'Australia', '', '', '', 'nao'),
(11, 'Austria', '', '', '', 'nao'),
(12, 'Azerbaijan', '', '', '', 'nao'),
(13, 'Bahamas', '', '', '', 'nao'),
(14, 'Bahrain', '', '', '', 'nao'),
(15, 'Bangladesh', '', '', '', 'nao'),
(16, 'Barbados', '', '', '', 'nao'),
(17, 'Belarus', '', '', '', 'nao'),
(18, 'Belgium', '', '', '', 'nao'),
(19, 'Belize', '', '', '', 'nao'),
(20, 'Benin', '', '', '', 'nao'),
(21, 'Bhutan', '', '', '', 'nao'),
(22, 'Bolivia', '', '', '', 'nao'),
(23, 'Bosnia and Herz.', '', '', '', 'nao'),
(24, 'Botswana', '', '', '', 'nao'),
(25, 'Brazil', '', '', '', 'nao'),
(26, 'Brunei', '', '', '', 'nao'),
(27, 'Bulgaria', '', '', '', 'nao'),
(28, 'Burkina Faso', '', '', '', 'nao'),
(29, 'Burundi', '', '', '', 'nao'),
(30, 'Cambodia', '', '', '', 'nao'),
(31, 'Cameroon', '', '', '', 'nao'),
(32, 'Canada', '', '', '', 'nao'),
(33, 'Cabo Verde', '', '', '', 'nao'),
(34, 'Central African Rep.', '', '', '', 'nao'),
(35, 'Chad', '', '', '', 'nao'),
(36, 'Chile', '', '', '', 'nao'),
(37, 'China', '', '', '', 'nao'),
(38, 'Colombia', '', '', '', 'nao'),
(39, 'Comoros', '', '', '', 'nao'),
(40, 'Congo', '', '', '', 'nao'),
(41, 'Dem. Rep. Congo', '', '', '', 'nao'),
(42, 'Costa Rica', '', '', '', 'nao'),
(43, 'Croatia', '', '', '', 'nao'),
(44, 'Cuba', '', '', '', 'nao'),
(45, 'Cyprus', '', '', '', 'nao'),
(46, 'N. Cyprus', '', '', '', 'nao'),
(47, 'Czechia', '', '', '', 'nao'),
(48, 'Denmark', '', '', '', 'nao'),
(49, 'Faeroe Is.', '', '', '', 'nao'),
(50, 'Greenland', '', '', '', 'nao'),
(51, 'Djibouti', '', '', '', 'nao'),
(52, 'Dominica', '', '', '', 'nao'),
(53, 'Dominican Rep.', '', '', '', 'nao'),
(54, 'Ecuador', '', '', '', 'nao'),
(55, 'Egypt', '', '', '', 'nao'),
(56, 'El Salvador', '', '', '', 'nao'),
(57, 'Eq. Guinea', '', '', '', 'nao'),
(58, 'Eritrea', '', '', '', 'nao'),
(59, 'Estonia', '', '', '', 'nao'),
(60, 'Eswatini', '', '', '', 'nao'),
(61, 'Ethiopia', '', '', '', 'nao'),
(62, 'Fiji', '', '', '', 'nao'),
(63, 'Finland', '', '', '', 'nao'),
(64, 'Åland', '', '', '', 'nao'),
(65, 'Fr. S. Antarctic Lands', '', '', '', 'nao'),
(66, 'French Polynesia', '', '', '', 'nao'),
(67, 'Wallis and Futuna Is.', '', '', '', 'nao'),
(68, 'St. Pierre and Miquelon', '', '', '', 'nao'),
(69, 'Gabon', '', '', '', 'nao'),
(70, 'Gambia', '', '', '', 'nao'),
(71, 'Georgia', '', '', '', 'nao'),
(72, 'Germany', '', '', '', 'nao'),
(73, 'Ghana', '', '', '', 'nao'),
(74, 'Greece', '', '', '', 'nao'),
(75, 'Grenada', '', '', '', 'nao'),
(76, 'Guatemala', '', '', '', 'nao'),
(77, 'Guinea', '', '', '', 'nao'),
(78, 'Guinea-Bissau', '', '', '', 'nao'),
(79, 'Guyana', '', '', '', 'nao'),
(80, 'Haiti', '', '', '', 'nao'),
(81, 'Honduras', '', '', '', 'nao'),
(82, 'Hungary', '', '', '', 'nao'),
(83, 'Iceland', '', '', '', 'nao'),
(84, 'India', '', '', '', 'nao'),
(85, 'Indonesia', '', '', '', 'nao'),
(86, 'Iran', '', '', '', 'nao'),
(87, 'Iraq', '', '', '', 'nao'),
(88, 'Ireland', '', '', '', 'nao'),
(89, 'Israel', '', '', '', 'nao'),
(90, 'Italy', '', '', '', 'nao'),
(91, 'Jamaica', '', '', '', 'nao'),
(92, 'Japan', '', '', '', 'nao'),
(93, 'Jordan', '', '', '', 'nao'),
(94, 'Kazakhstan', '', '', '', 'nao'),
(95, 'Kenya', '', '', '', 'nao'),
(96, 'Kiribati', '', '', '', 'nao'),
(97, 'Korea', '', '', '', 'nao'),
(98, 'Kosovo', '', '', '', 'nao'),
(99, 'Kuwait', '', '', '', 'nao'),
(100, 'Kyrgyzstan', '', '', '', 'nao'),
(101, 'Laos', '', '', '', 'nao'),
(102, 'Latvia', '', '', '', 'nao'),
(103, 'Lebanon', '', '', '', 'nao'),
(104, 'Lesotho', '', '', '', 'nao'),
(105, 'Liberia', '', '', '', 'nao'),
(106, 'Libya', '', '', '', 'nao'),
(107, 'Liechtenstein', '', '', '', 'nao'),
(108, 'Lithuania', '', '', '', 'nao'),
(109, 'Luxembourg', '', '', '', 'nao'),
(110, 'Macao', '', '', '', 'nao'),
(111, 'Macedonia', '', '', '', 'nao'),
(112, 'Madagascar', '', '', '', 'nao'),
(113, 'Malawi', '', '', '', 'nao'),
(114, 'Malaysia', '', '', '', 'nao'),
(115, 'Maldives', '', '', '', 'nao'),
(116, 'Mali', '', '', '', 'nao'),
(117, 'Malta', '', '', '', 'nao'),
(118, 'Marshall Is.', '', '', '', 'nao'),
(119, 'Martinique', '', '', '', 'nao'),
(120, 'Mauritania', '', '', '', 'nao'),
(121, 'Mauritius', '', '', '', 'nao'),
(122, 'Mayotte', '', '', '', 'nao'),
(123, 'Mexico', '', '', '', 'nao'),
(124, 'Micronesia', '', '', '', 'nao'),
(125, 'Moldova', '', '', '', 'nao'),
(126, 'Monaco', '', '', '', 'nao'),
(127, 'Mongolia', '', '', '', 'nao'),
(128, 'Montenegro', '', '', '', 'nao'),
(129, 'Montserrat', '', '', '', 'nao'),
(130, 'Morocco', '', '', '', 'nao'),
(131, 'Mozambique', '', '', '', 'nao'),
(132, 'Myanmar', '', '', '', 'nao'),
(133, 'Namibia', '', '', '', 'nao'),
(134, 'Nauru', '', '', '', 'nao'),
(135, 'Nepal', '', '', '', 'nao'),
(136, 'Netherlands', '', '', '', 'nao'),
(137, 'Netherlands Antilles', '', '', '', 'nao'),
(138, 'New Caledonia', '', '', '', 'nao'),
(139, 'New Zealand', '', '', '', 'nao'),
(140, 'Nicaragua', '', '', '', 'nao'),
(141, 'Niger', '', '', '', 'nao'),
(142, 'Nigeria', '', '', '', 'nao'),
(143, 'Niue', '', '', '', 'nao'),
(144, 'Norfolk Island', '', '', '', 'nao'),
(145, 'North Korea', '', '', '', 'nao'),
(146, 'Norway', '', '', '', 'nao'),
(147, 'Oman', '', '', '', 'nao'),
(148, 'Pakistan', '', '', '', 'nao'),
(149, 'Palau', '', '', '', 'nao'),
(150, 'Palestine', '', '', '', 'nao'),
(151, 'Panama', '', '', '', 'nao'),
(152, 'Papua New Guinea', '', '', '', 'nao'),
(153, 'Paraguay', '', '', '', 'nao'),
(154, 'Peru', '', '', '', 'nao'),
(155, 'Philippines', '', '', '', 'nao'),
(156, 'Pitcairn Is.', '', '', '', 'nao'),
(157, 'Poland', '', '', '', 'nao'),
(158, 'Portugal', '', '', '', 'nao'),
(159, 'Puerto Rico', '', '', '', 'nao'),
(160, 'Qatar', '', '', '', 'nao'),
(161, 'Réunion', '', '', '', 'nao'),
(162, 'Romania', '', '', '', 'nao'),
(163, 'Russia', '', '', '', 'nao'),
(164, 'Rwanda', '', '', '', 'nao'),
(165, 'S. Geo. and the Is.', '', '', '', 'nao'),
(166, 'Saint Helena', '', '', '', 'nao'),
(167, 'Saint Kitts and Nevis', '', '', '', 'nao'),
(168, 'Saint Lucia', '', '', '', 'nao'),
(169, 'Saint Vincent and the Grenadines', '', '', '', 'nao'),
(170, 'Samoa', '', '', '', 'nao'),
(171, 'San Marino', '', '', '', 'nao'),
(172, 'São Tomé and Príncipe', '', '', '', 'nao'),
(173, 'Saudi Arabia', '', '', '', 'nao'),
(174, 'Senegal', '', '', '', 'nao'),
(175, 'Serbia', '', '', '', 'nao'),
(176, 'Seychelles', '', '', '', 'nao'),
(177, 'Sierra Leone', '', '', '', 'nao'),
(178, 'Singapore', '', '', '', 'nao'),
(179, 'Slovakia', '', '', '', 'nao'),
(180, 'Slovenia', '', '', '', 'nao'),
(181, 'Solomon Is.', '', '', '', 'nao'),
(182, 'Somalia', '', '', '', 'nao'),
(183, 'South Africa', '', '', '', 'nao'),
(184, 'South Korea', '', '', '', 'nao'),
(185, 'South Sudan', '', '', '', 'nao'),
(186, 'Spain', '', '', '', 'nao'),
(187, 'Sri Lanka', '', '', '', 'nao'),
(188, 'Sudan', '', '', '', 'nao'),
(189, 'Suriname', '', '', '', 'nao'),
(190, 'Sweden', '', '', '', 'nao'),
(191, 'Switzerland', '', '', '', 'nao'),
(192, 'Syria', '', '', '', 'nao'),
(193, 'Taiwan', '', '', '', 'nao'),
(194, 'Tajikistan', '', '', '', 'nao'),
(195, 'Tanzania', '', '', '', 'nao'),
(196, 'Thailand', '', '', '', 'nao'),
(197, 'Timor-Leste', '', '', '', 'nao'),
(198, 'Togo', '', '', '', 'nao'),
(199, 'Tonga', '', '', '', 'nao'),
(200, 'Trinidad and Tobago', '', '', '', 'nao'),
(201, 'Tunisia', '', '', '', 'nao'),
(202, 'Turkey', '', '', '', 'nao'),
(203, 'Turkmenistan', '', '', '', 'nao'),
(204, 'Turks and Caicos Is.', '', '', '', 'nao'),
(205, 'Tuvalu', '', '', '', 'nao'),
(206, 'Uganda', '', '', '', 'nao'),
(207, 'Ukraine', '', '', '', 'nao'),
(208, 'United Arab Emirates', '', '', '', 'nao'),
(209, 'United Kingdom', '', '', '', 'nao'),
(210, 'United States of America', '', '', '', 'nao'),
(211, 'Uruguay', '', '', '', 'nao'),
(212, 'Uzbekistan', '', '', '', 'nao'),
(213, 'Vanuatu', '', '', '', 'nao'),
(214, 'Vatican', '', '', '', 'nao'),
(215, 'Venezuela', '', '', '', 'nao'),
(216, 'Vietnam', '', '', '', 'nao'),
(217, 'Wallis and Futuna', '', '', '', 'nao'),
(218, 'Western Sahara', '', '', '', 'nao'),
(219, 'Yemen', '', '', '', 'nao'),
(220, 'Zambia', '', '', '', 'nao'),
(221, 'Zimbabwe', '', '', '', 'nao'),
(222, 'Siachen Glacier', '', '', '', 'nao'),
(223, 'Antarctica', '', '', '', 'nao'),
(224, 'Norwegian Antarctic Territory', '', '', '', 'nao'),
(225, 'Svalbard', '', '', '', 'nao'),
(226, 'Heard Island and McDonald Islands', '', '', '', 'nao'),
(227, 'British Indian Ocean Territory', '', '', '', 'nao'),
(228, 'Indian Ocean Territory', '', '', '', 'nao'),
(229, 'Clipperton Island', '', '', '', 'nao'),
(230, 'Saba', '', '', '', 'nao'),
(231, 'Bonaire', '', '', '', 'nao'),
(232, 'Sint Eustatius', '', '', '', 'nao'),
(233, 'Saint Martin', '', '', '', 'nao'),
(234, 'Saint Barthélemy', '', '', '', 'nao'),
(235, 'Guadeloupe', '', '', '', 'nao'),
(236, 'Saint Pierre and Miquelon', '', '', '', 'nao'),
(237, 'Martinique', '', '', '', 'nao'),
(238, 'Montserrat', '', '', '', 'nao'),
(239, 'Anguilla', '', '', '', 'nao'),
(240, 'Bermuda', '', '', '', 'nao'),
(241, 'British Virgin Islands', '', '', '', 'nao'),
(242, 'Cayman Islands', '', '', '', 'nao'),
(243, 'Turks and Caicos Islands', '', '', '', 'nao'),
(244, 'Montserrat', '', '', '', 'nao'),
(245, 'Pitcairn Islands', '', '', '', 'nao'),
(246, 'Tokelau', '', '', '', 'nao'),
(247, 'Cook Islands', '', '', '', 'nao'),
(248, 'Niue', '', '', '', 'nao'),
(249, 'American Samoa', '', '', '', 'nao'),
(250, 'Guam', '', '', '', 'nao'),
(251, 'Northern Mariana Islands', '', '', '', 'nao'),
(252, 'Palmyra Atoll', '', '', '', 'nao'),
(253, 'Wake Island', '', '', '', 'nao'),
(254, 'Midway Atoll', '', '', '', 'nao'),
(255, 'Jarvis Island', '', '', '', 'nao'),
(256, 'Baker Island', '', '', '', 'nao'),
(257, 'Howland Island', '', '', '', 'nao'),
(258, 'Johnston Atoll', '', '', '', 'nao'),
(259, 'Kingman Reef', '', '', '', 'nao'),
(260, 'Navassa Island', '', '', '', 'nao'),
(261, 'Serranilla Bank', '', '', '', 'nao'),
(262, 'Bajo Nuevo Bank', '', '', '', 'nao');
